### ISSUE TITLE
make_stereo_panorama.cpp not build 

### ISSUE THREAD

**Issue by Ankit-Kumar-Saini** [jonathanventura/spherical-sfm#2]
When I build the project, the two files (undistort_images, run_spherical_sfm) were build successfully. However, make_stereo_panorama isn't build in the process. The build process didn't show any errors or messages, regarding why this file isn't build. I am attaching the build folder content for reference.
![build_folder_content](https://user-images.githubusercontent.com/60767873/187820460-667842da-9464-486a-9025-b0f5e40dc5ca.png)

**Comment by limacv** [comment]
邮件已送达 马力的邮箱

**Comment by jonathanventura** [comment]
You need to specifically enable it in the cmake configuration.  The flag is BUILD_STITCHER:

    cmake .. -DBUILD_STITCHER=TRUE

I will add this to the README -- sorry for the confusion.
